# Generated by Django 3.1.1 on 2020-10-15 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20201015_2203'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
