# Generated by Django 3.1.1 on 2020-10-17 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_delete_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
        migrations.RemoveField(
            model_name='news',
            name='video',
        ),
    ]
