# Generated by Django 3.1.1 on 2020-10-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=260, unique=True)),
                ('name', models.CharField(blank=True, max_length=260)),
            ],
        ),
    ]
